// Rankingstevner v0.22.2 – offisiell WA-ranking + offisielt rankinggrunnlag + korrekt hekk per kjønn
(function(){'use strict';
const eventSelect=document.getElementById('event'),sex=document.getElementById('sex'),waInput=document.getElementById('waProfileId'),waStatus=document.getElementById('waProfileStatus'),legacy=document.getElementById('waProfileDetails');if(!eventSelect||!sex||!waInput||!legacy)return;
let mount=document.getElementById('officialWaRankingDetails');if(!mount){mount=document.createElement('div');mount.id='officialWaRankingDetails';mount.style.cssText='display:block;margin-top:14px;margin-bottom:8px;padding:14px;border:1px solid #d9e5e1;border-radius:10px;background:#fff';legacy.insertAdjacentElement('afterend',mount);}let requestSeq=0;
const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const label=()=>eventSelect.options[eventSelect.selectedIndex]?.textContent||eventSelect.value;const validScore=v=>Number.isFinite(Number(v))&&Number(v)>0;
function ensureSexSpecificHurdle(){
  const women=sex.value==='W',want=women?'100mH':'110mH',wrong=women?'110mH':'100mH',wantLabel=women?'100 m hekk':'110 m hekk';
  const wasWrong=eventSelect.value===wrong;
  [...eventSelect.options].filter(o=>o.value===wrong).forEach(o=>o.remove());
  let wanted=[...eventSelect.options].find(o=>o.value===want);
  if(!wanted){
    wanted=document.createElement('option');wanted.value=want;wanted.textContent=wantLabel;
    const before=[...eventSelect.options].find(o=>o.value==='400mH');
    if(before)eventSelect.insertBefore(wanted,before);else eventSelect.appendChild(wanted);
  }else wanted.textContent=wantLabel;
  if(wasWrong){eventSelect.value=want;setTimeout(()=>eventSelect.dispatchEvent(new Event('change',{bubbles:true})),0);}
}
function fmtDate(v){if(!v)return'–';const d=new Date(v);if(Number.isNaN(d.getTime()))return esc(v);return d.toLocaleDateString('no-NO',{day:'2-digit',month:'2-digit',year:'numeric'});}
function renderLoading(){mount.innerHTML=`<strong>Rankinggrunnlag for ${label()}:</strong><br><span class="muted">Henter offisiell ranking fra World Athletics …</span>`;}
function renderNone(d){const diag=esc(JSON.stringify(d?.diagnostics??d??{},null,2));mount.innerHTML=`<strong>Rankinggrunnlag for ${label()}:</strong><br><span class="muted">Ingen verifisert WA-ranking funnet for denne øvelsen.</span><details style="margin-top:10px"><summary style="cursor:pointer;font-weight:700">WA-diagnostikk</summary><pre style="white-space:pre-wrap;word-break:break-word;font-size:12px;background:#f7f9fb;padding:10px;border-radius:8px;margin-top:8px">${diag}</pre></details>`;window.__rankingstevnerOfficialRanking=null;}
function basisHtml(data,heading){const rows=Array.isArray(data?.basis)?data.basis:[];if(!rows.length)return `<div class="muted">Offisiell Ranking Score er hentet, men WA leverte ikke detaljert rankinggrunnlag i dette oppslaget.</div>`;return `<div><strong>Tellende rankinggrunnlag i ${esc(heading)} fra World Athletics:</strong><div style="overflow-x:auto;margin-top:7px"><table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th style="text-align:left;padding:6px">Dato</th><th style="text-align:left;padding:6px">Stevne</th><th style="text-align:left;padding:6px">Kat.</th><th style="text-align:left;padding:6px">Resultat</th><th style="text-align:right;padding:6px">Result Score</th><th style="text-align:right;padding:6px">Placing Score</th><th style="text-align:right;padding:6px">Performance Score</th></tr></thead><tbody>${rows.map(r=>`<tr style="border-top:1px solid #e5ecea"><td style="padding:6px">${fmtDate(r.date)}</td><td style="padding:6px">${esc(r.competition||'–')}</td><td style="padding:6px">${esc(r.category||'–')}</td><td style="padding:6px">${esc(r.result??r.mark??'–')}</td><td style="padding:6px;text-align:right">${r.resultScore??'–'}</td><td style="padding:6px;text-align:right">${r.placingScore??'–'}</td><td style="padding:6px;text-align:right;font-weight:700">${r.performanceScore??'–'}</td></tr>`).join('')}</tbody></table></div>${validScore(data.averagePerformanceScore)?`<div style="font-size:12px;color:#677585;margin-top:8px">Gjennomsnitt av tellende Performance Scores: <strong>${Number(data.averagePerformanceScore)}</strong></div>`:''}</div>`;}
function render(data){const score=Number(data.score),rank=Number(data.rank),hasRank=Number.isFinite(rank)&&rank>0,heading=label();mount.innerHTML=`<div style="display:grid;grid-template-columns:minmax(0,1fr) 260px;gap:18px;align-items:stretch"><div>${basisHtml(data,heading)}</div><div style="background:#f7fbfa;border:1px solid #cfe2dc;border-radius:14px;padding:22px 18px;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center"><div style="font-size:13px;letter-spacing:.12em;font-weight:900;color:#0f766e">OFFISIELL WA RANKING SCORE</div><div style="font-size:52px;line-height:1;font-weight:900;color:#0b4f4a;margin:14px 0 10px">${score}</div>${hasRank?`<div style="font-size:16px;font-weight:800;color:#0f766e;margin-bottom:6px">#${rank} i verden</div>`:''}</div></div>`;window.__rankingstevnerOfficialRanking={event:eventSelect.value,score,rank:hasRank?rank:null,basis:Array.isArray(data.basis)?data.basis:[],source:'World Athletics official ranking calculation'};window.dispatchEvent(new CustomEvent('rankingofficialloaded'));}
async function fetchOnce(id,seq){const res=await fetch(`/api/wa-official-ranking?id=${encodeURIComponent(id)}&event=${encodeURIComponent(eventSelect.value)}&sex=${encodeURIComponent(sex.value)}&v=222&t=${Date.now()}`,{cache:'no-store'}),data=await res.json();if(seq!==requestSeq)return null;return data;}
async function load(){ensureSexSpecificHurdle();const id=waInput.value.trim().match(/(\d{7,9})/)?.[1]||'';if(!id){mount.innerHTML='';return;}const seq=++requestSeq;renderLoading();let last=null;for(let a=0;a<3;a++){try{const d=await fetchOnce(id,seq);last=d;if(seq!==requestSeq)return;if(d?.ok&&d?.verifiedPublished===true&&validScore(d?.score)){render(d);return;}}catch(e){last={ok:false,error:String(e?.message||e)};}if(a<2)await new Promise(r=>setTimeout(r,350*(a+1)));}if(seq===requestSeq)renderNone(last);}
eventSelect.addEventListener('change',()=>setTimeout(load,80));sex.addEventListener('change',()=>{setTimeout(()=>{ensureSexSpecificHurdle();load();},120);});waInput.addEventListener('change',()=>setTimeout(load,20));if(waStatus)new MutationObserver(()=>{if(waInput.value.trim())setTimeout(()=>{ensureSexSpecificHurdle();load();},60);}).observe(waStatus,{childList:true,subtree:true,characterData:true});setTimeout(()=>{ensureSexSpecificHurdle();load();},500);})();
